#!/usr/bin/env python3
"""Generate src/gen_logo.h: the joypad logo as an LOGO_H x LOGO_W
byte-per-pixel mask (1 = silhouette, 0 = transparent).

Reads ../assets/logo_64.png. The PNG is intentionally non-square
(76x64 from 3do/assets/) so it renders ~square on the N64's
anamorphic 320x240 framebuffer (each fb pixel = 2 TV dots wide).
Byte-per-pixel encoding is simpler than bit-packing for non-
power-of-2 widths and the data fits in ~5 KB.
"""

import sys
from pathlib import Path
from PIL import Image

SCRIPT  = Path(__file__).resolve()
ROOT    = SCRIPT.parent.parent
SRC_PNG = ROOT / "assets" / "logo_64.png"
OUT_H   = ROOT / "src" / "gen_logo.h"


def main():
    img = Image.open(SRC_PNG).convert("L")
    w, h = img.size

    lines = [
        "/* gen_logo.h -- auto-generated by buildtools/make_logo.py.",
        f" * {w}x{h} 1-bit logo mask, byte-per-pixel. 1 = silhouette,",
        " * 0 = transparent. Source PNG uses BLACK for the silhouette",
        " * (the project convention -- see make_logo.py for inversion",
        " * note). Do not edit by hand. */",
        "#ifndef N64_GEN_LOGO_H",
        "#define N64_GEN_LOGO_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define LOGO_W {w}",
        f"#define LOGO_H {h}",
        "",
        "static const uint8_t gen_logo[LOGO_H * LOGO_W] = {",
    ]
    for y in range(h):
        row_bytes = []
        for x in range(w):
            # PNG convention in this project: BLACK = silhouette,
            # WHITE = background. Flag silhouette pixels with 1.
            row_bytes.append("1" if img.getpixel((x, y)) < 128 else "0")
        lines.append("    " + ",".join(row_bytes) + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")

    OUT_H.write_text("\n".join(lines))
    print(f"[make_logo.py] wrote {OUT_H} (mask {w}x{h})")


if __name__ == "__main__":
    sys.exit(main())
