#!/usr/bin/env python3
"""Generate ppc/gen_logo.h: a 1-bit alpha mask of the joypad logo for the
screensaver.

Source: branding/screensaver-logo.png (preferred) or
        branding/logo.png (fallback) or
        ../../branding/logo_solid.png (joypad shared)

The mask gets rendered each frame in the cycle color so the screensaver
can color-shift on every wall bounce while the silhouette stays crisp.
"""

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

LOGO_W = 160
LOGO_H = 160
LOGO_SMALL_W = 64
LOGO_SMALL_H = 64

TITLE_TEXT = 'Joypad Test Suite'
TITLE_FONT_SIZE = 36

FONT_CANDIDATES = [
    '/System/Library/Fonts/Helvetica.ttc',
    '/System/Library/Fonts/Supplemental/Arial Bold.ttf',
    '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf',
    '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf',
]


def find_font() -> str:
    for p in FONT_CANDIDATES:
        if Path(p).exists():
            return p
    return None

HERE = Path(__file__).parent
PROJECT = HERE.parent
OUT = PROJECT / 'ppc' / 'gen_logo.h'

CANDIDATES = [
    PROJECT / 'branding' / 'screensaver-logo.png',
    PROJECT / 'branding' / 'logo.png',
]


def find_source() -> Path:
    for p in CANDIDATES:
        if p.exists():
            return p
    sys.exit('No source PNG found; tried: ' + ', '.join(str(p) for p in CANDIDATES))


def pack_mask(flat: Image.Image, w: int, h: int):
    """Resize `flat` (grayscale, dark = silhouette) to w×h and pack into a
    1-bit alpha mask (MSB-first per byte)."""
    scaled = flat.resize((w, h), Image.LANCZOS)
    bytes_per_row = w // 8
    packed = bytearray(bytes_per_row * h)
    lit = 0
    for y in range(h):
        for x in range(w):
            if scaled.getpixel((x, y)) < 128:
                packed[y * bytes_per_row + x // 8] |= 0x80 >> (x % 8)
                lit += 1
    return packed, bytes_per_row, lit


def emit_mask(f, name: str, w: int, h: int, packed: bytes,
              bytes_per_row: int, lit: int) -> None:
    upper = name.upper()
    f.write(f'// {w}x{h} mask, {lit} lit px.\n')
    f.write(f'#define {upper}_W {w}\n')
    f.write(f'#define {upper}_H {h}\n')
    f.write(f'#define {upper}_BYTES_PER_ROW {bytes_per_row}\n')
    f.write(f'static const unsigned char {name}_mask[{len(packed)}] = {{\n')
    line = []
    for i, b in enumerate(packed):
        line.append(f'0x{b:02x}')
        if (i + 1) % 16 == 0:
            f.write('  ' + ', '.join(line) + ',\n')
            line = []
    if line:
        f.write('  ' + ', '.join(line) + ',\n')
    f.write('};\n\n')


def render_title_bitmap():
    """Render TITLE_TEXT into a 1-bit mask suitable for direct XFB blits.
    Width is rounded up to a multiple of 16 (XFB pairs + byte packing)."""
    font_path = find_font()
    if not font_path:
        sys.exit('No system font found for title rendering.')
    font = ImageFont.truetype(font_path, TITLE_FONT_SIZE)

    measure = Image.new('L', (1, 1))
    md = ImageDraw.Draw(measure)
    bbox = md.textbbox((0, 0), TITLE_TEXT, font=font)
    text_w = bbox[2] - bbox[0]
    text_h = bbox[3] - bbox[1]
    # Pad horizontally to a multiple of 16 (8 for byte packing, 2 for XFB).
    canvas_w = ((text_w + 15) // 16) * 16
    # Pad vertically a touch so descenders aren't clipped.
    canvas_h = text_h + 4

    img = Image.new('L', (canvas_w, canvas_h), 0)
    d = ImageDraw.Draw(img)
    d.text((-bbox[0], -bbox[1] + 2), TITLE_TEXT, fill=255, font=font)

    # Pack: bright pixels (text) are "lit". Inverse threshold from logo case.
    bytes_per_row = canvas_w // 8
    packed = bytearray(bytes_per_row * canvas_h)
    lit = 0
    for y in range(canvas_h):
        for x in range(canvas_w):
            if img.getpixel((x, y)) > 128:
                packed[y * bytes_per_row + x // 8] |= 0x80 >> (x % 8)
                lit += 1
    return packed, bytes_per_row, lit, canvas_w, canvas_h


def main() -> None:
    src = find_source()
    img = Image.open(src).convert('RGBA')
    bg = Image.new('RGBA', img.size, (255, 255, 255, 255))
    flat = Image.alpha_composite(bg, img).convert('L')

    big = pack_mask(flat, LOGO_W, LOGO_H)
    small = pack_mask(flat, LOGO_SMALL_W, LOGO_SMALL_H)
    title_packed, title_bpr, title_lit, title_w, title_h = render_title_bitmap()

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open('w') as f:
        f.write('// Auto-generated by buildtools/make_logo.py — DO NOT EDIT.\n')
        f.write(f'// Source: {src}\n\n')
        f.write('#ifndef GEN_LOGO_H\n#define GEN_LOGO_H\n\n')
        emit_mask(f, 'logo', LOGO_W, LOGO_H, big[0], big[1], big[2])
        emit_mask(f, 'logo_small', LOGO_SMALL_W, LOGO_SMALL_H,
                  small[0], small[1], small[2])
        emit_mask(f, 'title', title_w, title_h, title_packed, title_bpr, title_lit)
        f.write('#endif  // GEN_LOGO_H\n')
    print(f'wrote {OUT} (big {big[2]} lit, small {small[2]} lit, '
          f'title {title_w}x{title_h})')


if __name__ == '__main__':
    main()
